spring:
  batch:
    job:
      names: ExportJpaPagingJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch
    username: study
    password: 1234
    
logging:
  level:
    '[com.example.demo]': debug
    
mybatis:
  mapper-locations: classpath*:/mapper/postgresql/*.xml
  type-aliases-package: com.example.demo.domain.model